name: git_checkout_from_cache
description: Checkout git from cache
runs:
  using: composite
  steps:
  - name: restore_cache
    uses: actions/cache@v3.3.1
    with:
      key: source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
      path: UPDATE_ME
      restore-keys: |-
        source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
        source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
        source-v{{ .Environment.CACHE_VERSION }}-
  - name: Fetch git tags
    run: |-
      mkdir -p ~/.ssh
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      # Fetch tags if git cache is present
      if [ -e /home/circleci/project/.git ]
      then
        git fetch origin --tags
      fi
    shell: bash
  - uses: actions/checkout@v3.6.0
  # - name: Compress git objects
  #   run: git gc
  #   shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.1
    with:
      path: ".git"
      key: source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
