name: npm_install_from_cache
description: Install npm packages from cache
runs:
  using: composite
  steps:
  - name: Cache node modules
    id: cache-nodemodules
    uses: actions/cache/restore@v3
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

  - name: Clear master cache
    if: ${{ steps.cache-nodemodules.outputs.cache-hit == 'true' }}
    run: |
        owner="binary-com"
        repo="deriv-app"
        cache_key="${{ steps.cache-nodemodules.outputs.cache-matched-key }}"
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ github.token }}" \
          https://api.github.com/repos/$owner/$repo/actions/caches?key=$cache_key
    shell: bash

  - name: Install npm packages
    if: steps.cache-nodemodules.outputs.cache-hit != 'true'
    run: npm ci
    shell: bash

  - name: Bootstrap
    run: npm run bootstrap:ci
    shell: bash
  - name: save_cache
    uses: actions/cache/save@v3
    with:
      path: |-
        node_modules
        packages/account/node_modules
        packages/api/node_modules
        packages/appstore/node_modules
        packages/bot-skeleton/node_modules
        packages/bot-web-ui/node_modules
        packages/cashier/node_modules
        packages/components/node_modules
        packages/core/node_modules
        packages/hooks/node_modules
        packages/cfd/node_modules
        packages/indicators/node_modules
        packages/p2p/node_modules
        packages/reports/node_modules
        packages/shared/node_modules
        packages/stores/node_modules
        packages/trader/node_modules
        packages/translations/node_modules
        packages/utils/node_modules
        packages/analytics/node_modules
        packages/wallets/node_modules
      key: ${{ steps.cache-nodemodules.outputs.cache-matched-key }}
