on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Reporter
    runs-on: Runner_16cores
    container:
      image: node:18.16.0
    steps:

      - uses: actions/checkout@v3
      - name: Checkout Repository
        uses: "./.github/actions/git_checkout_from_cache"
      - name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"
      - name: Run tests
        run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
